feature: Fix deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,18 +18,6 @@ jobs:
         service_account_key: ${{ secrets.GCP_SA_KEY }}
         export_default_credentials: true
 
-    - name: Clean gcloud configuration
-      run: |
-        gcloud config configurations activate default
-        gcloud config unset account
-        gcloud config unset project
-
-
-    - name: Verify gcloud authentication
-      run: |
-        gcloud auth list
-        gcloud config list
-
     - name: Modify app.yaml with environment variables
       run: |
         echo "env_variables:" >> app.yaml
@@ -38,4 +26,8 @@ jobs:
 
     - name: Deploy to App Engine
       run: |
-        gcloud app deploy --quiet
+        try:
+          gcloud app deploy --quiet
+        except:
+          echo "Error during deployment"
+          exit 1
